#Project RHYMES
server:
  port: 18080
#JSP config
  servlet:
    jsp:
      init-parameters:
        development: true
#custume error page
  error:
    whitelabel:
      enabled: true

spring:
  #db config
  datasource: 
    hikari:
      jdbc-url: jdbc:mysql://112.169.197.59:23306/rhymes?characterEncoding=UTF-8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: mhj
      password: mhj
  #ehcache config
  cache:    ehcache:      config: classpath:/config/ehcache.xml
      
#jsp
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      file-size-threshold: 10MB
      
logging:
  level: 
    org:
     apache:
      tiles:
       request:
        locale:
         PostfixedApplicationResource: ERROR