#Spring Security Exam Project With Book
server:
  port: 18080
#JSP config
  servlet:
    jsp:
      init-parameters:
        development: true
#custume error page
  error:
    whitelabel:
      enabled: true

#db config
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://192.168.0.14:3306/rhymes?characterEncoding=UTF-8&serverTimezone=UTC
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: mhj
      password: mhj
#jsp
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
        